version: '3'

services: 

  app:
    build: 
      context: ./app
    image: danielmarini/app:latest
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh npx nodemon index.js 3000
    networks: 
      - node-network
    volumes: 
      - ./app/src:/usr/src/app
    depends_on: 
       - db

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: danielmarini/nginx:latest
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
#    volumes: 
#      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

    

networks: 
  node-network:
    driver: bridge      
